# Generated by Codex on 2026-04-30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('ETB', 'Ethiopian Birr'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound')], default='ETB', max_length=3)),
                ('theme_mode', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', max_length=10)),
                ('font_family', models.CharField(choices=[('inter', 'Inter'), ('poppins', 'Poppins')], default='inter', max_length=10)),
                ('font_size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='medium', max_length=10)),
                ('primary_color', models.CharField(default='indigo', max_length=20)),
                ('compact_tables', models.BooleanField(default=False)),
                ('dashboard_default_view', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=10)),
                ('dashboard_chart_type', models.CharField(choices=[('bar', 'Bar'), ('pie', 'Pie'), ('line', 'Line')], default='line', max_length=10)),
                ('dashboard_show_income_expense_chart', models.BooleanField(default=True)),
                ('dashboard_show_budget_summary', models.BooleanField(default=True)),
                ('dashboard_show_top_categories', models.BooleanField(default=True)),
                ('notifications_budget_alerts', models.BooleanField(default=True)),
                ('notifications_goal_reminders', models.BooleanField(default=True)),
                ('notifications_low_balance', models.BooleanField(default=True)),
                ('budget_threshold', models.PositiveSmallIntegerField(default=80)),
                ('export_data_ready', models.BooleanField(default=False)),
                ('google_oauth_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='accounts.user')),
            ],
        ),
    ]
